//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantisSharp
{
  public partial class Status
  {
    #region Fields

    private int _id;

    private string _name;

    private string _color;

    private string _label;


    #endregion

    #region Properties

    public int Id
    {
      get { return _id; }
      internal set { _id = value; }
    }

    public string Name
    {
      get { return _name; }
      internal set { _name = value; }
    }

    public string Color
    {
      get { return _color; }
      internal set { _color = value; }
    }

    public string Label
    {
      get { return _label; }
      internal set { _label = value; }
    }



    #endregion

    #region Methods

    public override string ToString()
    {
      return _name;
    }

    #endregion

  }
}

